### ISSUE TITLE
Custom URL link directs to del.dog domain instead of host.

### ISSUE THREAD

**Issue by codywarmbo** [dogbin/server#11]
![image](https://user-images.githubusercontent.com/43068195/74598359-cd88ba00-5035-11ea-9981-b0e5618fe1d8.png)
Once a paste is made with a custom URL, the link to that URL at the top of the page redirects to the `del.dog` domain instead of the local IP or whatever domain is being used.

**Comment by SuperSandro2000** [comment]
I am not 100% sure but I think the ``https://del.dog`` in [this](https://github.com/dogbin/dogbin/blob/master/app/resources/templates/index.peb#L24) needs to be dropped.

**Comment by codywarmbo** [comment]
Thanks, if I'm using the docker, do you know how I can access that file to change it?

**Comment by SuperSandro2000** [comment]
This file is compiled into the jar. You need to change it and recompile the jar/docker image.

**Comment by codywarmbo** [comment]
Seems a little more complex than I hoped! Any tips where to look/start for accomplishing that?

**Comment by SuperSandro2000** [comment]
I will do a PR in a few minutes and then it will be in the next version.
It was also a bit more complicated than I thought.
If you can't wait then you would need to do:
1. Clone my fork and checkout the branch of the PR
2. Build the dogbin image with ``docker build . -t dogbin/dogbin``
3. run docker-compose

Also there is https://github.com/dogbin/dogbin/blob/master/app/resources/templates/includes/base.peb#L39 left which I don't currently know how to fix. Maybe @deletescape can do that?

The PR is #13

**Comment by codywarmbo** [comment]
That is fantastic. I can be patient. Thanks so much!

**Comment by nyancrimew** [comment]
The remaining instances of the del.dog domain in Templates should be fixable by getting the host via the config which is already wired into the template logic

**Comment by SuperSandro2000** [comment]
I must admit I have no idea how to do this.

**Comment by pavog** [comment]
@SuperSandro2000 

I think [index.peb](https://github.com/dogbin/dogbin/blob/master/app/resources/templates/index.peb#L74) contains a good example for this. 

**To sum it up:**
Use `{# @pebvariable name="appConfig" type="dog.del.app.config.AppConfig" #}` at the beginning of each template file that contains the host (statically) to setup the appConfig and use `appConfig.host` in all the places where you want to replace the del.dog domain.
