### ISSUE TITLE
Add this in my android phone

### ISSUE THREAD

**Issue by itsdani121** [dogbin/server#26]
hi , I don't know about this after my friend's phone I saw that when an app crash it gives me a link to log report of bug report why it crashes which opens in the new dogbin link. so what is possible way which i implement it in my phone or how to set it kindly guide me about this i don't know about it all

**Comment by SuperCosmicBeing** [comment]
> hi , I don't know about this after my friend's phone I saw that when an app crash it gives me a link to log report of bug report why it crashes which opens in the new dogbin link. so what is possible way which i implement it in my phone or how to set it kindly guide me about this i don't know about it all

It's probably a feature of the OS or rom that your friend uses. There's no simple way to do that without applying that patch to the source code of rom and then building it again. Instead I'd suggest you use "FC Catcher" app. It will log all crashes and keep it so you can copy paste it yourself to a pastebin. Also not sure if it needs root or not
