### ISSUE TITLE
Smooth scrolling doesn’t work on ios

### ISSUE THREAD

**Issue by rupansh** [dogbin/server#4]
Dev pls fix

**Comment by SphericalKat** [comment]
Wow pero saar

**Comment by smartass02** [comment]
Disable animations, Oh wait No....

**Comment by smartass08** [comment]
Just Disable animations, Oh wait .....

**Comment by rupansh** [comment]
~~Trying to roast with two differen't accounts....~~ Oh wait... its smartass! nothing can be done
